### ISSUE TITLE
groovy.json.JsonException: expecting '}' or ',' but got current char '\' with an int value of 92

### ISSUE THREAD

**Issue by yermilov** [pocket-square/pocket-square-articles#1]
16:03:08.777 [taskExecutor-2] WARN  c.g.p.a.s.ArticlesIngestService - failed during ingesting articles for user with id=58b1800bc9e77c0001d1d701 since 1491895076 because of class groovy.json.JsonException: expecting '}' or ',' but got current char '\' with an int value of 92

The current character read is '\' with an int value of 92
expecting '}' or ',' but got current char '\' with an int value of 92
line number 2
index number 188474
<script src="\&quot;https://d3js.org/d3.v4.js\&quot;"></script>
.............^
groovy.json.JsonException: expecting '}' or ',' but got current char '\' with an int value of 92

The current character read is '\' with an int value of 92
expecting '}' or ',' but got current char '\' with an int value of 92
line number 2
index number 188474
<script src="\&quot;https://d3js.org/d3.v4.js\&quot;"></script>
.............^
        at groovy.json.internal.JsonParserCharArray.complain(JsonParserCharArray.java:153)
        at groovy.json.internal.JsonParserCharArray.decodeJsonObject(JsonParserCharArray.java:144)
        at groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:186)
        at groovy.json.internal.JsonParserCharArray.decodeJsonObject(JsonParserCharArray.java:132)
        at groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:186)
        at groovy.json.internal.JsonParserCharArray.decodeValue(JsonParserCharArray.java:157)
        at groovy.json.internal.JsonParserCharArray.decodeFromChars(JsonParserCharArray.java:46)
        at groovy.json.internal.JsonParserCharArray.parse(JsonParserCharArray.java:384)
        at groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:107)
        at groovy.json.JsonSlurper.parseText(JsonSlurper.java:205)
        at groovy.json.JsonSlurper$parseText$0.call(Unknown Source)
        at com.github.pocketsquare.articles.service.ArticlesIngestService$1.act(ArticlesIngestService.groovy:76)
        at com.github.pocketsquare.articles.service.ArticlesIngestService$1$act$1.call(Unknown Source)
        at io.github.yermilov.kerivnyk.service.KerivnykService.executeDurableJob(KerivnykService.groovy:202)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1092)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:408)
        at groovy.lang.Closure.run(Closure.java:495)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by yermilov** [comment]
"1627647543": {"status": "0", "is_index": "0", "sort_id": 74, "time_updated": "1491997852", "time_favorited": "0", "time_read": "0", "excerpt": "First, include d3 and d3-horizon-chart on the web page:
  <script src="\&quot;https://d3js.org/d3.v4.js\&quot;"></script>
  <script src="\&quot;https://unpkg.com/d3-horizon-chart\&quot;"></script> To draw a horizon chart use the d3.horizonChart() generator: var horizonChart = d3.horizonChart() .height(80) .", "has_image": "0", "favorite": "0", "has_video": "0", "word_count": "115", "given_title": "http://kmandov.github.io/d3-horizon-chart/", "resolved_url": "http://kmandov.github.io/d3-horizon-chart/", "is_article": "1", "item_id": "1627647543", "time_added": "1491997852", "resolved_id": "1627647543", "given_url": "http://kmandov.github.io/d3-horizon-chart/", "resolved_title": "D3 Horizon Charts"}, "1658781169": {"status": "0", "is_index": "1", "sort_id": 66, "time_updated": "1491997832", "time_favorited": "0", "time_read": "0", "excerpt": "", "has_image": "0", "favorite": "0", "has_video": "0", "word_count": "0", "given_title": "http://dood.al/pinktrombone/", "resolved_url": "https://dood.al/pinktrombone/", "is_article": "0", "item_id": "1658781169", "time_added": "1491997832", "resolved_id": "1658781169", "given_url": "http://dood.al/pinktrombone/", "resolved_title": "Pink Trombone"},
